-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgRaiGMEDDBTLAT89a
q6vJxi41VoXkqx1c/EE4LZnOIvigCgYIKoZIzj0DAQehRANCAAREY8r0NwVzw/pW
7JlSxW+D/cJNZxS+TjFjeZZm4i9poCPDX6TbLxqumTZmdxHdMxtDd4k4qjP6P4wb
Iz8BQ0ut
-----END PRIVATE KEY-----