name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create package-lock.json
        run: echo "" > package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Create .env file
        run: echo "${{secrets.PROD_ENV}}" > .env

      - name: Create service account file
        run: echo '${{secrets.SERVICE_ACCOUNT}}' > src/api/helpers/goollooper-service.json

      - name: Edit package
        run: if [ -e "node_modules/mongoose-paginate-v2/index.d.ts" ]; then sed -i 's/LeanDocument/Document/'  node_modules/mongoose-paginate-v2/index.d.ts; else echo "File not found"; fi

      - name: Build
        run: npm run build

      - name: Restart Server
        run: pm2 restart apis-goolooper
