name: Pull & Deploy
on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Deploy NodeJS App
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST_PROD}}
          key: ${{secrets.SSH_KEY_PROD}}
          username: ${{secrets.SSH_USERNAME_PROD}}
          script: |
            cd /home/mod/goollooper-backend
            git pull origin main
            npm install
            echo '${{secrets.SERVICE_ACCOUNT}}' > src/api/helpers/goollooper-service.json
            npm run build
            pm2 restart apis-goollooper
            pm2 list
